### PR TITLE
feat(heater enable/disable capability for gen 3 remote): make heater …

### PR DESCRIPTION
**Pull request by dsdevries**
…capability available for gen 3 remote

### CODE REVIEW

**Comment by kjeet90** [comment]
We can't just rename the id of the capability/flows. That will cause breaking changes for existing users. I believe there are two options:

1: Add a own capability that does the same for gen3 as for the iqc. It will be duplicate, but it'll not break anything for existing users.
2: Deprecate the iqc capability and add one like you've done here, but would need to read up on SDK documentation how/if it's possible to do it this.

I won't have time to look into this right now unfortunately, but I can read up on it when I have time. 

In the meantime you can just install this PR through CLI and have it working for you, but I guess you've already got that in place :+1:

**Comment by dsdevries** [comment]
> We can't just rename the id of the capability/flows. That will cause breaking changes for existing users. I believe there are two options:
> 
> 1: Add a own capability that does the same for gen3 as for the iqc. It will be duplicate, but it'll not break anything for existing users. 2: Deprecate the iqc capability and add one like you've done here, but would need to read up on SDK documentation how/if it's possible to do it this.
> 
> I won't have time to look into this right now unfortunately, but I can read up on it when I have time.
> 
> In the meantime you can just install this PR through CLI and have it working for you, but I guess you've already got that in place 👍

Good point, I will go for option one, keep the original capabilities the same, and make my own for the gen3 remote.

**Comment by dsdevries** [comment]
I made the changes. It should work ok now

**Comment by kjeet90** [comment]
A few more things needs to be added for it to work properly, but I can fix that after the merge.

**Pull request merged**
